In [1]:
import numpy as np
import gymnasium as gym
import random
import time
from IPython.display import clear_output

In [2]:
env = gym.make('FrozenLake-v1', render_mode='ansi')

In [3]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

In [4]:
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [45]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001 #check out with 0.01 - the output in inconsistent

In [46]:
rewards_all_episodes = []

![q_value_update](C:\Vishnu\Projects\frozen_lake\images\q_value_update.png)

In [47]:
for episode in range(num_episodes):
    state = env.reset()[0]
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode): 
        
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) 
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, truncated, info = env.step(action)
        
        # Update Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))    
        
        state = new_state
        rewards_current_episode += reward 
        
        if done == True: 
            break

            
    # Exploration rate decay
    # Exploration vs exploitation
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    
    rewards_all_episodes.append(rewards_current_episode)

In [48]:
# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000

********Average reward per thousand episodes********

1000 :  0.03400000000000002
2000 :  0.09200000000000007
3000 :  0.23200000000000018
4000 :  0.33800000000000024
5000 :  0.3860000000000003
6000 :  0.5050000000000003
7000 :  0.5450000000000004
8000 :  0.5360000000000004
9000 :  0.4850000000000004
10000 :  0.5590000000000004


In [12]:
# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)



********Q-table********

[[0.54169066 0.53730282 0.537426   0.521727  ]
 [0.28644927 0.28711701 0.28938817 0.53293219]
 [0.44258282 0.42824429 0.42310411 0.50290932]
 [0.35610927 0.26813022 0.33527225 0.47730216]
 [0.56595107 0.47548313 0.40654147 0.29269947]
 [0.         0.         0.         0.        ]
 [0.19940345 0.22622565 0.32572063 0.11738323]
 [0.         0.         0.         0.        ]
 [0.40750096 0.40333023 0.52453904 0.61698867]
 [0.43205696 0.69226806 0.31040717 0.29373523]
 [0.65313054 0.19450454 0.42386756 0.36065477]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.3920228  0.49976524 0.83693406 0.47525903]
 [0.73921247 0.93801342 0.77198108 0.74001224]
 [0.         0.         0.         0.        ]]


In [51]:
# Watch our agent play Frozen Lake by playing the best action 
# from each state according to the Q-table

for episode in range(3):
    state = env.reset()[0]
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)

    for step in range(max_steps_per_episode):        
        clear_output(wait=True)
        print(env.render())
        time.sleep(0.3)

        action = np.argmax(q_table[state,:])        
        new_state, reward, done, truncated, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            print(env.render())
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                print("****You fell through a hole!****")
                time.sleep(3)
                clear_output(wait=True)
            break
        state = new_state

env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG

****You reached the goal!****
